# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-25 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorthim_Category',
            fields=[
                ('Category_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Category_description', models.TextField()),
            ],
        ),
    ]
