# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-25 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Algorthims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorthim',
            fields=[
                ('Algorthim_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Algorthim_name', models.TextField()),
                ('Algorthim_Content', models.TextField()),
                ('Algorthim_Code', models.TextField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Algorthims.Algorthim_Category', verbose_name='Category')),
            ],
        ),
    ]
